CREATE TABLE IF NOT EXISTS content_items (
  id SERIAL PRIMARY KEY,
  page_slug TEXT NOT NULL,
  content_key TEXT NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (page_slug, content_key)
);

CREATE INDEX IF NOT EXISTS content_items_page_idx ON content_items (page_slug);

INSERT INTO content_items (page_slug, content_key, value)
VALUES
  ('global', 'navHomeLabel', 'Home'),
  ('global', 'navAboutLabel', 'About'),
  ('global', 'navProjectsLabel', 'Projects'),
  ('global', 'navContactLabel', 'Contact'),
  ('global', 'navAdminLabel', 'Admin'),
  ('global', 'featuredProjectsTitle', 'Featured Projects'),
  ('global', 'featuredProjectsLink', 'View all →'),
  ('global', 'dashboardTitle', 'Dashboard'),
  ('global', 'footerLine', '© 2025 {name} - All Services Nominal'),
  ('global', 'footerStats', '{views} views • {commits} commits'),
  ('profile', 'name', 'Alibek Isomov'),
  ('profile', 'role', 'Middle Software Engineer'),
  ('profile', 'company', 'Gross Insurance'),
  ('profile', 'bio', 'I build software that helps people at scale. Obsessed with clean code, developer experience, and aesthetics.'),
  ('profile', 'location', 'Tashkent, Uzbekisan'),
  ('profile', 'email', 'aisomov.dev@gmail.com'),
  ('profile', 'github', 'https://github.com'),
  ('profile', 'linkedin', 'https://linkedin.com'),
  ('profile', 'views', '885,353'),
  ('profile', 'commits', '1,240'),
  ('home', 'heroBadgePrefix', 'Currently working @'),
  ('home', 'heroGreeting', 'Hey! I''m'),
  ('home', 'heroRoleLine', 'I''m currently working as a {role} @ {company}.'),
  ('home', 'heroTrustedLine', 'I''ve written software that is trusted by {trusted}.'),
  ('home', 'heroTrustedEmphasis', 'major organizations'),
  ('home', 'heroClosing', 'Seeing code I wrote actually help people at scale is what keeps me building. Currently building AI that helps people articulate their ideas and share them at scale.'),
  ('home', 'heroGithubLabel', 'GitHub'),
  ('home', 'heroLinkedinLabel', 'LinkedIn'),
  ('home', 'heroMoreLabel', 'More about me'),
  ('home', 'dashboardConnectTitle', 'Let''s Connect'),
  ('home', 'dashboardConnectBody', 'Always open to interesting projects and conversations.'),
  ('home', 'dashboardConnectButton', 'Book a Chat'),
  ('home', 'dashboardBasedInLabel', 'Based In'),
  ('home', 'dashboardClicksLabel', 'Clicks'),
  ('home', 'dashboardClicksHint', 'Try clicking me!'),
  ('home', 'dashboardCommitsTitle', 'Recent Commits'),
  ('home', 'dashboardLanguageTitle', 'Language Stats'),
  ('home', 'dashboardLanguageGo', 'Go 40%'),
  ('home', 'dashboardLanguageJs', 'JS 30%'),
  ('home', 'dashboardLanguageTs', 'TS 20%'),
  ('about', 'pageTitle', 'About Me'),
  ('about', 'backgroundTitle', 'Background'),
  ('about', 'backgroundBody', 'I''m a passionate developer with a focus on building scalable, performant web applications. My journey in tech started with a curiosity about how things work, which led me to dive deep into software engineering.'),
  ('about', 'interestsTitle', 'Interests'),
  ('about', 'interestsItem1', 'Full-stack web development'),
  ('about', 'interestsItem2', 'Open source contributions'),
  ('about', 'interestsItem3', 'Developer experience & tooling'),
  ('about', 'interestsItem4', 'Clean code architecture'),
  ('about', 'interestsItem5', 'Performance optimization'),
  ('about', 'skillsTitle', 'Skills'),
  ('about', 'skillsLanguagesTitle', 'Languages'),
  ('about', 'skillsLanguagesBody', 'Go, JavaScript, TypeScript, Python'),
  ('about', 'skillsFrontendTitle', 'Frontend'),
  ('about', 'skillsFrontendBody', 'React, Next.js, Tailwind CSS, Vite'),
  ('about', 'skillsBackendTitle', 'Backend & DevOps'),
  ('about', 'skillsBackendBody', 'Node.js, Docker, Redis, PostgreSQL'),
  ('contact', 'pageTitle', 'Get in Touch'),
  ('contact', 'pageSubtitle', 'Have a project in mind or want to collaborate? I''d love to hear from you!'),
  ('contact', 'formTitle', 'Send me a message'),
  ('contact', 'formNameLabel', 'Name'),
  ('contact', 'formNamePlaceholder', 'Your name'),
  ('contact', 'formEmailLabel', 'Email'),
  ('contact', 'formEmailPlaceholder', 'your@email.com'),
  ('contact', 'formMessageLabel', 'Message'),
  ('contact', 'formMessagePlaceholder', 'Your message here...'),
  ('contact', 'formSubmitLabel', 'Send Message'),
  ('contact', 'formSuccessMessage', 'Thanks for reaching out! I''ll get back to you soon.'),
  ('contact', 'infoEmailLabel', 'Email'),
  ('contact', 'infoLinkedinLabel', 'LinkedIn'),
  ('contact', 'infoGithubLabel', 'GitHub'),
  ('contact', 'infoLinkedinCta', 'Connect with me'),
  ('contact', 'infoGithubCta', 'Check out my repos'),
  ('projects', 'pageTitle', 'All Projects'),
  ('projects', 'ctaTitle', 'Want to collaborate?'),
  ('projects', 'ctaBody', 'I''m always interested in working on exciting projects. Feel free to reach out!'),
  ('projects', 'ctaButton', 'Get in Touch')
ON CONFLICT (page_slug, content_key) DO NOTHING;
